// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxwQpGqVC8FcWdAezc7dMomPtYiT0PKw',
    appId: '1:994206147938:android:ce6352503d32b0fbb5783b',
    messagingSenderId: '994206147938',
    projectId: 'shop-app-54892',
    storageBucket: 'shop-app-54892.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIrMnumuEtLqLUj48sxNvGPMQ6FeSDLbQ',
    appId: '1:994206147938:ios:a5f62d46d27d354ab5783b',
    messagingSenderId: '994206147938',
    projectId: 'shop-app-54892',
    storageBucket: 'shop-app-54892.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7FT0S_eHh4lXjkP0ve6Yjxu0RdNsJcM0',
    appId: '1:994206147938:web:61f1be7e8dac94cdb5783b',
    messagingSenderId: '994206147938',
    projectId: 'shop-app-54892',
    authDomain: 'shop-app-54892.firebaseapp.com',
    storageBucket: 'shop-app-54892.firebasestorage.app',
    measurementId: 'G-VVL6KGCFYC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIrMnumuEtLqLUj48sxNvGPMQ6FeSDLbQ',
    appId: '1:994206147938:ios:a5f62d46d27d354ab5783b',
    messagingSenderId: '994206147938',
    projectId: 'shop-app-54892',
    storageBucket: 'shop-app-54892.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7FT0S_eHh4lXjkP0ve6Yjxu0RdNsJcM0',
    appId: '1:994206147938:web:67030d8b4b2409e9b5783b',
    messagingSenderId: '994206147938',
    projectId: 'shop-app-54892',
    authDomain: 'shop-app-54892.firebaseapp.com',
    storageBucket: 'shop-app-54892.firebasestorage.app',
    measurementId: 'G-THZLJPL2Y3',
  );

}